# Generated by Django 5.0.6 on 2024-07-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nmae',
            new_name='name',
        ),
    ]
